import { parseTimezone, settingsError, type SettingsResult } from "pi-orchestrator/person-settings-contract";
export { parseTimezone };
export type { PersonTimezone, SettingsResult } from "pi-orchestrator/person-settings-contract";
export type SettingOwner = { component: string; location: string; command: string | null };
export type SettingDefinition = { id: string; label: string; description: string; scope: "person" | "system"; kind: "timezone" | "boolean" | "owner"; owner: SettingOwner; activation: string };
export type SettingValue = { state: "set"; value: unknown } | { state: "unset" } | { state: "unavailable"; message: string };
export type SettingEntry = { definition: SettingDefinition; value: SettingValue; editable: boolean };
export type SettingsSnapshot = { administrator: boolean; entries: SettingEntry[] };
const person = (id: string, label: string, description: string, kind: SettingDefinition["kind"], component: string, location: string, command: string | null, activation: string): SettingDefinition => ({ id, label, description, scope: "person", kind, owner: { component, location, command }, activation });
const system = (id: string, label: string, description: string, component: string, location: string, command: string, activation: string): SettingDefinition => ({ id, label, description, scope: "system", kind: "owner", owner: { component, location, command }, activation });
export const SETTINGS = Object.freeze([
  person("person.timezone", "Timezone", "An explicit IANA timezone or a client observation with provenance. Explicit selection wins over device observations.", "timezone", "Person settings", "$PI_REMOTE_DATA/settings.json", null, "Next message delivery and calendar read"),
  person("person.autoCollapse", "Auto-collapse work and thoughts", "One preference for this person's chats, shared by their devices.", "boolean", "Person settings", "$PI_REMOTE_DATA/settings.json", null, "Next app refresh"),
  person("person.threads", "Thread models and execution", "Model, thinking, speed, timeout and other choices belong to each thread, not a second settings copy.", "owner", "Thread service", "Thread settings API /v1/sessions/:id/settings", "pi-orchestrator --help", "Immediately; running turns use the thread owner's transition policy"),
  person("device.phone", "Phone control and Android grants", "Phone enabled state and overlay visibility are device preferences. Android permissions are independent grants, not enable switches.", "owner", "Kenan Android", "KenanRemote phoneStatus / phoneConfigure / phoneOverlay; mandatory native permission setup", "pi-phone catalogue", "After Android reports the resulting state"),
  person("device.notifications", "Notifications", "Browser or Android permission and this device's notification behavior.", "owner", "Notification provider", "Browser notification permission / KenanRemote notifications", null, "This device"),
  person("device.updates", "App updates", "Install only the verified update offered by the owning updater.", "owner", "App updater", "KenanRemote app updates / /v1/app-update", null, "After verified app restart"),
  person("person.connection", "Account and environment", "This person's authenticated account, folder unlock and granted environments.", "owner", "Router sessions", "EnvironmentControl / authenticated router sessions", null, "Next authenticated connection"),
  person("person.memory", "Memory and calendar data", "Private Markdown memory, authority pointers and calendar datasets remain in this person's custody.", "owner", "Core memory", "Declared memory folder; memory_data calendar operations", null, "After the owning memory operation commits"),
  person("person.agent", "Agent packages, extensions and tools", "Per-person agent instructions and installed extension configuration; credentials stay in the owner's secret store.", "owner", "Pi agent", "$PI_AGENT_DIR/settings.json; $PI_AGENT_DIR/models.json; AGENTS.md", "pi --help", "Next agent session / owning extension reload"),
  person("person.browser", "Browser profiles and access", "Only the person's own browser sessions, profiles and allowed-domain configuration.", "owner", "Agent browser", "agent-browser profiles; pi-agent-browser-config", "pi-agent-browser-config --help", "Next browser launch"),
  system("system.host", "Host identity and topology", "Host/environment identity, model routes and service declarations.", "Pi Stack host", "$PI_STACK_HOST_CONFIG / /etc/pi-stack/host.json", "systemctl cat pi-remote-router.service", "Validated host reconciliation"),
  system("system.accounts", "Accounts, grants and limits", "Person registrations, destinations/environment grants, model-broker account credentials and weekly limits. Secret values are never returned by Settings.", "Account and model broker owners", "/var/lib/pi-remote/persons/*.json; /etc/pi-stack/users/*; /etc/pi-stack/model-broker*.json", "pi-account --help; pi-remote person --help", "Owning account/broker reconciliation"),
  system("system.models", "Model catalog and provider routing", "Configured providers/models, agent capacity and account affinity. Available model switches below write the existing model availability owner.", "Orchestrator model catalog", "$PI_AGENT_DIR/models.json; /etc/pi-stack/agent-capacity*.json; model broker configuration", "pi-model-selection-doctor --help; pi-agent-capacity --help", "Owning catalog/broker reload"),
  system("system.destinations", "Destinations and workspaces", "Destination models, workspace roots and context directories within explicit grants.", "Core / workspace admission", "PI_REMOTE_DESTINATIONS; PI_REMOTE_THREAD_DESTINATIONS; declared core scopes", "pi-remote --help", "Owning scope reconciliation"),
  system("system.runtime", "Agent runtime and lifecycle", "Shared execution custody, launch credentials and resource admission.", "Pi Stack core", "/etc/pi-stack/core.json; /etc/pi-stack/core-runtime.json", "systemctl cat pi-stack-core.service", "Core custody transfer preserves live sessions"),
  system("system.router", "Router, login and private network", "Bind addresses, upstream credentials, OIDC/login and private-network/mesh ingress configuration. Credentials are not exposed here.", "Remote router", "/etc/pi-stack; /etc/systemd/system/pi-remote-router.service.d", "systemctl cat pi-remote-router.service", "Router restart"),
  system("system.phone", "Phone and overlay services", "Phone broker/call provider endpoints, device transport and overlay service configuration; Android grants remain device-owned.", "Phone service", "/etc/pi-stack; /etc/systemd/system/pi-phone@.service.d; PI_PHONE_* / PI_REMOTE_PHONE_*", "systemctl cat pi-phone@kenan.service; pi-phone --help", "Owning phone service restart"),
  system("system.meet", "Meet and telephone audio", "External browser meetings, local transcription and telephone audio endpoints.", "Meet / telephone transport", "/etc/pi-stack; PI_VOICE_*; PI_CALL_*", "pi-call --help", "Owning transport reconciliation"),
  system("system.memory", "Memory, custody, rooms and journal", "Shared custody, per-person encrypted stores, room/runtime endpoints and action-journal publication grants.", "Kenan memory / root / rooms", "/etc/pi-stack; /etc/systemd/system/pi-rooms.service.d; one-kenan configuration", "systemctl cat pi-rooms.service", "Owning custody/room service reconciliation"),
  system("system.updates", "Web and Android update publication", "Verified app bundle selection, signing credential location and host update routing.", "App update / host publication", "/var/lib/pi-remote/app-updates/current; /etc/pi-stack/publication.json", "pi-stack-publication --help", "Publication receipt confirms activation"),
  system("system.publication", "Source publication and deployment", "Repository source custody, two-host release targets, immutable build inputs, service checks and Android transfer.", "Pi Stack publication", "/etc/pi-stack/publication.json; config/packages.json; config/skills.json; config/tools.json", "pi-stack-publication --help", "Next accepted combined publication"),
  system("system.services", "Feature services and integrations", "Host-only environment/service configuration not edited by a browser. See the owning locations; no generic arbitrary configuration editor.", "Ubuntu host deployment", "/etc/pi-stack; deploy/host; deploy/ubuntu; /etc/systemd/system/pi-*.service.d", "systemctl list-unit-files 'pi-*'", "Owning service's declared restart/reconciliation"),
] satisfies SettingDefinition[]);
export function settingDefinition(id: string): SettingDefinition | null { return SETTINGS.find(setting => setting.id === id) ?? null; }
export function modelAvailabilityDefinition(id: string, label: string, location: string): SettingDefinition {
  return { id: `model.available:${id}`, label, description: "Host-wide availability; writes the model catalog's existing availability policy.", scope: "system", kind: "boolean", owner: { component: "Model availability", location, command: null }, activation: "Immediately; does not terminate existing turns" };
}
export function machineActionDefinition(id: string, label: string): SettingDefinition {
  return { id: `machine.action:${id}`, label, description: "Writes the existing machine action owner, not a duplicate desired-state store.", scope: "system", kind: "boolean", owner: { component: "Machine actions", location: "/v1/actions", command: null }, activation: "After owning service confirms state" };
}
export function validateSettingValue(definition: SettingDefinition, value: unknown): SettingsResult<unknown> {
  if (definition.kind === "owner") return settingsError("owner-managed", `Use ${definition.owner.component} at ${definition.owner.location}`);
  if (value === null && definition.scope === "person") return { ok: true, value: null };
  if (definition.kind === "boolean") return typeof value === "boolean" ? { ok: true, value } : settingsError("invalid", "Setting requires a boolean");
  const parsed = parseTimezone(value, new Date().toISOString());
  return parsed.ok ? { ok: true, value: parsed.value } : parsed;
}
