import { afterEach, expect, test } from "bun:test";
import { Database } from "bun:sqlite";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { captureAuxiliary, runAuxiliary, type AuxiliaryPlan } from "./core-auxiliary";
const dirs: string[] = [];
afterEach(() => { for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true }); });
function fixture() {
  const dir = mkdtempSync(join(tmpdir(), "core-aux-")); dirs.push(dir);
  const threadsPath = join(dir, "threads.sqlite3"), supervisorPath = join(dir, "supervisor.sqlite3"), session = join(dir, "session.jsonl");
  writeFileSync(session, JSON.stringify({ type: "message", id: "native", parentId: null, message: { role: "assistant", content: "PRIVATE_BODY_NOT_EXPORTED" } }) + "\n");
  const db = new Database(threadsPath);
  db.exec("CREATE TABLE thread(id TEXT,session_file TEXT,held INTEGER,metadata TEXT,created_at INTEGER); CREATE TABLE thread_wake(thread_id TEXT,data TEXT)");
  db.query("INSERT INTO thread VALUES(?,?,?,?,?)").run("manager", session, 1, JSON.stringify({ manager: true, archived: false, private: "PRIVATE_BODY_NOT_EXPORTED" }), Date.now() - 10000);
  db.query("INSERT INTO thread_wake VALUES(?,?)").run("manager", "PRIVATE_BODY_NOT_EXPORTED"); db.close();
  const ui = new Database(supervisorPath);
  ui.exec("CREATE TABLE manager_view(singleton INTEGER,thread_id TEXT,initialized INTEGER,view TEXT); INSERT INTO manager_view VALUES(1,'manager',1,'mono'); CREATE TABLE metadata(key TEXT,value TEXT)");
  for (const [key, value] of [["thread-settlements:person", "12"], ["thread-attention:person", "3"], ["thread-questions:person", "8"], ["manager-origin:child", "other-host"]]) ui.query("INSERT INTO metadata VALUES(?,?)").run(key!, value!);
  ui.close();
  const ident = (path: string) => { const s = statSync(path, { bigint: true }); return { path, dev: String(s.dev), ino: String(s.ino) }; };
  const plan: AuxiliaryPlan = { version: 1, phase: "baseline", outputPath: join(dir, "out.json"), baselinePath: null, baselineSha256: null, scopes: [{ id: "person:one", availability: "available", threads: ident(threadsPath), supervisor: ident(supervisorPath), sessionRoots: [dir], manager: { kind: "supervisor" }, managerRouting: { kind: "configured", relay: { scopeId: "person:one", adoptedOrigins: [] }, notices: { notificationOwnerId: "person" } }, images: null, duties: null, missingCursor: { kind: "reject" }, detachedReceiptPath: null, liveOwner: null }] };
  return { plan, dir, session, supervisorPath };
}
test("captures exact manager identity/cursors/origins/held state without private bodies", () => {
  const { plan } = fixture(), result = captureAuxiliary(plan);
  expect(result.scopes[0]).toMatchObject({ manager: { kind: "existing", threadId: "manager" }, managerRouting: { notices: { notificationOwnerId: "person", adoptedCursors: { settlements: 12, attention: 3, questions: 8 } }, relay: { adoptedOrigins: [{ threadId: "child", environmentId: "other-host" }] } } });
  expect(result.evidence[0]!.retained).toEqual([{ id: "manager", held: true, archived: false, manager: true }]);
  expect(JSON.stringify(result)).not.toContain("PRIVATE_BODY_NOT_EXPORTED");
});
test.skipIf(process.getuid?.() !== 0)("CLI persists exact failure context and success without exporting bodies", () => {
  const { plan, dir, supervisorPath } = fixture();
  const planPath = join(dir, "plan.json");
  writeFileSync(planPath, JSON.stringify(plan), { mode: 0o600 });
  expect(runAuxiliary(planPath).ok).toBe(true);
  const successful = readFileSync(plan.outputPath, "utf8");
  expect(JSON.parse(readFileSync(`${plan.outputPath}.run.json`, "utf8")).state).toBe("complete");
  const ui = new Database(supervisorPath); ui.exec("DELETE FROM metadata WHERE key='thread-attention:person'"); ui.close();
  expect(runAuxiliary(planPath).ok).toBe(false);
  const receipt = readFileSync(`${plan.outputPath}.run.json`, "utf8");
  expect(JSON.parse(receipt)).toMatchObject({ state: "failed", progress: { scopeId: "person:one", stage: "scope" }, error: { code: "auxiliary-capture-unavailable" } });
  expect(receipt).not.toContain("PRIVATE_BODY_NOT_EXPORTED");
  expect(readFileSync(plan.outputPath, "utf8")).toBe(successful);
  expect(statSync(`${plan.outputPath}.run.json`).mode & 0o777).toBe(0o600);
});
test("missing cursors and invented no-manager states reject rather than default", () => {
  const { plan, supervisorPath } = fixture();
  const ui = new Database(supervisorPath); ui.exec("DELETE FROM metadata WHERE key='thread-attention:person'"); ui.close();
  expect(() => captureAuxiliary(plan)).toThrow("Missing original cursor");
  plan.scopes[0]!.manager = { kind: "none" };
  expect(() => captureAuxiliary(plan)).toThrow("Manager metadata exists");
});
test("unavailable scopes retain explicit configuration and never touch paths", () => {
  const { plan } = fixture();
  const scope = plan.scopes[0]!; scope.availability = "unavailable"; scope.threads = { path: "/missing/forbidden", dev: "1", ino: "1" }; scope.manager = { kind: "existing", threadId: "manager" };
  expect(captureAuxiliary(plan).evidence).toEqual([{ id: scope.id, state: "unavailable", touched: false }]);
});
test("image baseline records bounded native offsets under a live ingress owner", () => {
  const { plan, supervisorPath, dir } = fixture();
  const ui = new Database(supervisorPath); ui.exec("CREATE TABLE inline_images(id TEXT); CREATE TABLE inline_image_versions(id TEXT); CREATE TABLE inline_image_messages(id TEXT)"); ui.close();
  const scope = plan.scopes[0]!;
  expect(() => captureAuxiliary(plan)).toThrow("explicit owner");
  scope.images = { scopeId: scope.id, databasePath: supervisorPath, artifactRoot: join(dir, "images"), relatedThreadScopeIds: [] };
  const proc = readFileSync(`/proc/${process.pid}/stat`, "utf8");
  scope.liveOwner = { pid: process.pid, startTicks: proc.slice(proc.lastIndexOf(")") + 2).split(" ")[19]! };
  const result = captureAuxiliary(plan);
  expect(result.evidence[0]!.nativeImageSources).toMatchObject([{ threadId: "manager", lastOffset: 0, lastDigest: expect.stringMatching(/^[a-f0-9]{64}$/) }]);
  expect(JSON.stringify(result)).not.toContain("PRIVATE_BODY_NOT_EXPORTED");
  scope.sessionRoots = ["/not-the-owner"];
  expect(() => captureAuxiliary(plan)).toThrow("escapes registered");
});
test("watermark captures oversized historical records without parsing or exporting their bodies", () => {
  const { plan, supervisorPath, dir, session } = fixture();
  const scope = plan.scopes[0]!;
  const ui = new Database(supervisorPath); ui.exec("CREATE TABLE inline_images(id TEXT); CREATE TABLE inline_image_versions(id TEXT); CREATE TABLE inline_image_messages(id TEXT)"); ui.close();
  scope.images = { scopeId: scope.id, databasePath: supervisorPath, artifactRoot: join(dir, "images"), relatedThreadScopeIds: [] };
  const proc = readFileSync(`/proc/${process.pid}/stat`, "utf8");
  scope.liveOwner = { pid: process.pid, startTicks: proc.slice(proc.lastIndexOf(")") + 2).split(" ")[19]! };
  writeFileSync(session, JSON.stringify({ type: "message", id: "large-tool", message: { role: "toolResult", content: "z".repeat(9 * 1024 * 1024) } }) + "\n");
  const source = captureAuxiliary(plan).evidence[0]!.nativeImageSources[0];
  expect(source.size).toBeGreaterThan(8 * 1024 * 1024);
  expect(source.closedOffset).toBe(source.size);
  expect(source.prefixDigest).toMatch(/^[a-f0-9]{64}$/);
  expect(JSON.stringify(source).length).toBeLessThan(1500);
});
test("one declared image registry captures related fleet sources sharing its Remote projection", () => {
  const f = fixture(), related = fixture();
  const scope = f.plan.scopes[0]!, fleet = related.plan.scopes[0]!;
  const db = new Database(fleet.threads!.path); db.exec("UPDATE thread SET id='fleet-thread',metadata='{}'"); db.close();
  fleet.id = "fleet:one"; fleet.manager = { kind: "none" }; fleet.managerRouting = { kind: "none" }; fleet.supervisor = scope.supervisor;
  const ui = new Database(f.supervisorPath); ui.exec("CREATE TABLE inline_images(id TEXT); CREATE TABLE inline_image_versions(id TEXT); CREATE TABLE inline_image_messages(id TEXT)"); ui.close();
  scope.images = { scopeId: scope.id, databasePath: f.supervisorPath, artifactRoot: join(f.dir, "images"), relatedThreadScopeIds: [fleet.id] };
  const proc = readFileSync(`/proc/${process.pid}/stat`, "utf8");
  scope.liveOwner = { pid: process.pid, startTicks: proc.slice(proc.lastIndexOf(")") + 2).split(" ")[19]! };
  f.plan.scopes.push(fleet);
  const result = captureAuxiliary(f.plan);
  expect(result.images).toMatchObject({ kind: "configured", registries: [scope.images] });
  expect(result.evidence[0]!.nativeImageSources.map((row: any) => row.threadId)).toEqual(["manager", "fleet-thread"]);
  expect(result.evidence[1]!.nativeImageSources).toBeNull();
  expect(JSON.stringify(result)).not.toContain("PRIVATE_BODY_NOT_EXPORTED");
});
test("accepted watch spool remains in its existing store with metadata-only capture", () => {
  const { plan, supervisorPath } = fixture();
  const ui = new Database(supervisorPath);
  for (const table of ["watch_item", "watch_request", "watch_wake", "watch_delivery", "watch_schedule"]) ui.exec(`CREATE TABLE ${table}(id TEXT,body TEXT)`);
  ui.query("INSERT INTO watch_wake VALUES(?,?)").run("immutable-occurrence", "PRIVATE_BODY_NOT_EXPORTED"); ui.close();
  expect(() => captureAuxiliary(plan)).toThrow("existing-store duty owner");
  plan.scopes[0]!.duties = { scopeId: plan.scopes[0]!.id, path: "/declared/duties.md", watch: { kind: "existing", databasePath: supervisorPath, acceptedSpool: "hold" } };
  const result = captureAuxiliary(plan);
  expect(result.evidence[0]!.watch.find((row: any) => row.table === "watch_wake").rows[0].id).toBe("immutable-occurrence");
  expect(JSON.stringify(result)).not.toContain("PRIVATE_BODY_NOT_EXPORTED");
});
test("watch custody can share the exact thread database without being attributed to the supervisor", () => {
  const { plan } = fixture(), scope = plan.scopes[0]!;
  const db = new Database(scope.threads!.path);
  for (const table of ["watch_item", "watch_request", "watch_wake", "watch_delivery", "watch_schedule"]) db.exec(`CREATE TABLE ${table}(id TEXT,body TEXT)`);
  db.query("INSERT INTO watch_delivery VALUES(?,?)").run("accepted-id", "PRIVATE_BODY_NOT_EXPORTED"); db.close();
  scope.duties = { scopeId: scope.id, path: "/declared/duties.md", watch: { kind: "existing", databasePath: scope.supervisor!.path, acceptedSpool: "hold" } };
  expect(() => captureAuxiliary(plan)).toThrow("exact configured");
  scope.duties.watch.databasePath = scope.threads!.path;
  expect(captureAuxiliary(plan).evidence[0]!.watch.find((row: any) => row.table === "watch_delivery").rows[0].id).toBe("accepted-id");
});
(process.getuid?.() === 0 ? test : test.skip)("detached capture retains early watermarks and includes post-baseline sources without skipping output", () => {
  const { plan, supervisorPath, dir, session } = fixture();
  const scope = plan.scopes[0]!;
  const ui = new Database(supervisorPath);
  ui.exec("CREATE TABLE inline_images(id TEXT); CREATE TABLE inline_image_versions(id TEXT); CREATE TABLE inline_image_messages(id TEXT)");
  scope.images = { scopeId: scope.id, databasePath: supervisorPath, artifactRoot: join(dir, "images"), relatedThreadScopeIds: [] };
  const proc = readFileSync(`/proc/${process.pid}/stat`, "utf8");
  scope.liveOwner = { pid: process.pid, startTicks: proc.slice(proc.lastIndexOf(")") + 2).split(" ")[19]! };
  const threadDb = new Database(scope.threads!.path);
  threadDb.query("INSERT INTO thread VALUES(?,?,?,?,?)").run("unstarted", join(dir, "not-created.jsonl"), 0, "{}", Date.now() - 10000);
  const initial = captureAuxiliary(plan);
  const bytes = JSON.stringify(initial);
  plan.baselinePath = join(dir, "baseline.json"); writeFileSync(plan.baselinePath, bytes, { mode: 0o600 });
  plan.baselineSha256 = createHash("sha256").update(bytes).digest("hex");
  writeFileSync(session, readFileSync(session, "utf8") + JSON.stringify({ type: "message", id: "later", parentId: "native", message: { role: "assistant", content: "AFTER_BASELINE_PRIVATE" } }) + "\n");
  threadDb.query("INSERT INTO thread VALUES(?,?,?,?,?)").run("new-thread", join(dir, "new.jsonl"), 0, "{}", Date.now());
  threadDb.close();
  ui.exec("UPDATE metadata SET value='13' WHERE key='thread-settlements:person'"); ui.close();
  plan.phase = "detached";
  scope.detachedReceiptPath = join(dir, "detached.json");
  writeFileSync(scope.detachedReceiptPath, JSON.stringify({ state: "detached", scopeId: scope.id, databasePath: scope.threads!.path, databaseIdentity: scope.threads, previousOwner: { identity: "fixture-owner", detachedAt: new Date().toISOString() } }), { mode: 0o600 });
  const final = captureAuxiliary(plan);
  expect(final.evidence[0]!.nativeImageSources.find((r: any) => r.threadId === "manager")).toEqual(initial.evidence[0]!.nativeImageSources.find((r: any) => r.threadId === "manager"));
  expect(final.evidence[0]!.nativeImageSources.find((r: any) => r.threadId === "new-thread")).toMatchObject({ lastOffset: -1, revision: "created-after-baseline", priorSource: { kind: "created-after-baseline", baselineStartedAt: initial.startedAt } });
  expect(final.evidence[0]!.nativeImageSources.find((r: any) => r.threadId === "unstarted")).toMatchObject({ lastOffset: -1, revision: "unstarted", priorSource: { kind: "absent", observedAt: expect.any(String) } });
  expect(final.scopes[0]!.managerRouting.notices.adoptedCursors.settlements).toBe(13);
  expect(JSON.stringify(final)).not.toContain("AFTER_BASELINE_PRIVATE");
  writeFileSync(plan.baselinePath, bytes + " ");
  expect(() => captureAuxiliary(plan)).toThrow("Baseline custody changed");
});
