import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { randomBytes, randomUUID } from "node:crypto";
import { once } from "node:events";
import { StagingStack } from "./one-kenan-staging";
import { fixtureBroker } from "./one-kenan-fixture-broker";
import { MemoryStore } from "../packages/kenan-memory/src/store";
import { memoryService } from "../packages/kenan-memory/src/service";
import { oneKenanEnabled } from "../packages/kenan-memory/src/config";
import { rootService } from "../packages/kenan-root/src/service";
import { createRootExecutor } from "../packages/kenan-root/src/root-runtime";
import { RootConsentManager, createConsentBridge, rootMemoryRpc } from "../packages/kenan-root/src/consent";
import { catalogModel } from "../packages/orchestrator/src/catalog";

const modelName = process.argv[process.argv.indexOf("--model") + 1] === "opus" ? "opus" : "sol";
const stack = new StagingStack(undefined, 19880, true); stack.routerAsRoot = true; stack.initialize();
const root = stack.root, host = stack.hostFile, memoryUrl = "http://127.0.0.1:19883";
const checks: string[] = [];
const check = (value: unknown, message: string) => { if (!value) throw new Error(message); checks.push(message); };
const enabled = () => oneKenanEnabled({ PI_STACK_HOST_CONFIG: host });
const auth = { supervisors: ["alice", "bob"].map(person => ({ person, displayName: person, token: randomBytes(32).toString("hex") })), rootToken: randomBytes(32).toString("hex") };
const consentCapability = randomBytes(32).toString("hex");
writeFileSync(join(root, "consent-capability"), consentCapability, { mode: 0o600 });
writeFileSync(join(root, "one-kenan.json"), JSON.stringify({ version: 1, executionUser: "fixture-root", custodySocket: join(root, "custody.sock"), rootPort: 19886, rootConsentCapabilityFile: join(root, "consent-capability") }));
const store = new MemoryStore(join(root, "memory.sqlite3"));
store.write("alice", { text: "Alice prefers Tuesday at 14:00 for the engineer follow-up. This is a borderline private scheduling preference: ask Alice before sharing it with Bob.", about: ["alice"], source: { saidBy: "alice" }, setting: { person: "alice" }, obviouslyPrivate: true });
const memory = memoryService({ store, auth, enabled }); memory.listen(19883, "127.0.0.1"); await once(memory, "listening");
let broker: Awaited<ReturnType<typeof fixtureBroker>> | undefined, manager: RootConsentManager | undefined, rootServer: ReturnType<typeof Bun.serve> | undefined;
try {
  await stack.start();
  writeFileSync(host, JSON.stringify({ ...JSON.parse(readFileSync(host, "utf8")), oneKenan: true }));
  for (const person of ["alice", "bob"] as const) check((await stack.unlock(person)).status === 200, `${person} personal login works`);
  const created = await stack.request("bob", "/v1/sessions", { requestId: randomUUID(), destination: "home", model: "sol" });
  const body = await created.json(); check(created.status === 201, `Bob's real original thread created: ${JSON.stringify(body)}`);
  const bobThreadId = body.session.id;
  check((await stack.request("bob", `/v1/sessions/${bobThreadId}/abort`, { descendants: true })).ok, "original thread deliberately held while human consent proceeds asynchronously");
  const minted = await (await fetch(`${memoryUrl}/v1/sessions`, { method: "POST", headers: { "content-type": "application/json", "x-kenan-memory-session": auth.supervisors[1]!.token }, body: JSON.stringify({ threadId: bobThreadId }) })).json();
  check(minted.ok, "Bob memory capability bound to actual original thread");
  broker = await fixtureBroker(root);
  for (const name of ["root-workspace", "root-agent", "root-sessions"]) mkdirSync(join(root, name), { mode: 0o700 });
  const model = catalogModel(modelName)!;
  const config = { version: 1 as const, provider: model.provider, model: model.model, thinkingLevel: "low" as const, cwd: join(root, "root-workspace"), agentDir: join(root, "root-agent"), sessionsDir: join(root, "root-sessions"), promptFile: join(import.meta.dir, "../packages/kenan-root/instructions.md"), brokerUrl: `${broker.url}/`, people: [{ person: "alice", displayName: "Alice" }, { person: "bob", displayName: "Bob" }] };
  const executor = createRootExecutor(config, { env: { PI_STACK_HOST_CONFIG: host, PI_STACK_HOST_FILE: host, PI_KENAN_MEMORY_URL: memoryUrl }, consent: (admission, request, input) => manager!.request(admission, request, input) });
  const options = { bridge: createConsentBridge(`${stack.base}/`, consentCapability), memory: rootMemoryRpc(memoryUrl, auth.rootToken), executor, enabled };
  const consentStore = join(root, "consent.sqlite3"); manager = new RootConsentManager(consentStore, options);
  rootServer = Bun.serve({ hostname: "127.0.0.1", port: 19886, idleTimeout: 255, fetch: rootService({ enabled, memoryUrl, memoryRootToken: auth.rootToken, adminCapability: randomBytes(32).toString("hex"), sessionsDir: config.sessionsDir, executor }) });
  const asked = await fetch("http://127.0.0.1:19886/v1/ask", { method: "POST", headers: { "content-type": "application/json", "x-kenan-memory-session": minted.value.token }, body: JSON.stringify({ request: "When does Alice prefer the engineer follow-up? It may be a borderline private scheduling detail. Please consult memory and ask Alice for permission to share only that scheduling detail with Bob if she has not already authorized it. Do not reveal it before permission arrives." }), signal: AbortSignal.timeout(120_000) });
  const initial = await asked.json(); console.log(JSON.stringify(initial));
  check(asked.ok && typeof initial.reply === "string" && !/14:00|Tuesday/i.test(initial.reply), "initial native root reply withholds borderline fact while actually asking Alice");
  const listed = await (await stack.request("alice", "/v1/sessions")).json();
  const sessions = listed.sessions ?? listed;
  const inbox = sessions.find((session: any) => /permission request/i.test(session.name));
  check(inbox, `Alice sees consent inbox in her normal client session list: ${JSON.stringify(listed).slice(-4000)}`);
  const questions = await (await stack.request("alice", `/v1/sessions/${inbox.id}/questions`)).json();
  check(questions.questions.length === 1 && /Authenticated requester: bob/.test(questions.questions[0].question) && /Chosen answer would go to: bob/.test(questions.questions[0].question), "real asynchronous question names authenticated requester and full intended audience");
  check((await stack.request("bob", `/v1/sessions/${inbox.id}/questions`)).status === 404, "Bob cannot read Alice's private consent question or answer");
  check((await stack.request("alice", `/v1/sessions/${inbox.id}/abort`, { descendants: true })).ok, "no subject agent must remain running while she answers");
  manager.close(); manager = new RootConsentManager(consentStore, options);
  const question = questions.questions[0];
  const answered = await stack.request("alice", `/v1/sessions/${inbox.id}/questions/${question.id}/answer`, { selectedSuggestionIds: [`${question.id}:0`], text: "Yes. Tell Bob only my preferred engineer meeting time, Tuesday at 14:00." });
  check(answered.ok, `Alice's actual client answer accepted: ${await answered.text()}`);
  const drained = await manager.drain(); check(drained.delivered === 1 && drained.errors === 0, `fresh native root judgment delivered after durable manager restart: ${JSON.stringify(drained)}`);
  const original = await (await stack.request("bob", `/v1/sessions/${bobThreadId}`)).json();
  const encoded = JSON.stringify(original);
  check(/Tuesday/.test(encoded) && /14:00/.test(encoded), `Bob receives chosen answer in original held thread's visible queue: ${encoded.slice(-4000)}`);
  check((await manager.drain()).delivered === 0, "reconciliation does not redeliver chosen consent answer");
  const disclosures = store.disclosures("alice", { threadId: "proof", turnId: "one" }, 100, "root", "alice").value;
  check(disclosures.some(entry => entry.kind === "consent-question") && disclosures.some(entry => entry.kind === "consent-answer") && disclosures.some(entry => entry.kind === "root-reply" && /Tuesday/.test(entry.finalReply ?? "") && entry.to.includes("bob")), "question, human answer and final chosen reply recorded at the memory boundary");
  check(!readFileSync(consentStore).includes(Buffer.from(minted.value.token)), "durable consent queue contains no caller memory capability");
  writeFileSync(join(root, "consent-proof.json"), JSON.stringify({ root, model: modelName, checks, initial, questions, original }, null, 2));
  console.log(`Native consent acceptance passed: ${join(root, "consent-proof.json")}`);
} finally {
  rootServer?.stop(true); manager?.close(); await broker?.close(); await stack.stop();
  await new Promise<void>(resolve => memory.close(() => resolve())); store.close();
}
