name: test

on:
  push:
  pull_request:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stack:
    runs-on: [self-hosted, pi-stack]
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - name: check
        run: |
          source deploy/lib
          pi_stack_prepare_dependencies "$PWD"
          npm run check
